### create coupon
POST http://localhost:18888/api/v1
Content-Type: Application/json

{
  "name": "coupon1",
  "discount": 0,
  "discountType": "AMOUNT",
  "startDate": "2026-01-18T10:00:00",
  "endDate": "2026-02-18T10:00:00"
}