### create member
POST http://localhost:18888/api/v1/members
Content-Type: Application/json

{
  "name": "member1"
}

> {%
    client.global.set("memberId", response.body.id);
%}

### add coupon
POST http://localhost:18888/api/v1/members/coupons
Content-Type: Application/json

{
  "memberId": "{{memberId}}",
  "couponId": "{{couponId}}"
}

### get coupons
GET http://localhost:18888/api/v1/members/coupons?memberId={{memberId}}
Content-Type: Application/json

### delete coupon
DELETE http://localhost:18888/api/v1/members/coupons/{{couponId}}?memberId={{memberId}}
Content-Type: Application/json